[package]
name = "rtracer"
version = "0.1.0"
authors = ["Dave Challis <dave.challis@aistemos.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
rayon = "1.0"
image = "0.21"
indicatif = "0.11"
clap = "2.32"
base64 = "0.10"

[profile.release]
lto = true
